# Generated by Django 5.2.7 on 2026-05-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fix_product_category_on_delete_and_variant_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO Опис (Description)'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name='SEO Ключові слова'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='SEO Заголовок (Title)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO Опис (Description)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name='SEO Ключові слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='SEO Заголовок (Title)'),
        ),
    ]
