# Generated by Django 5.2.7 on 2026-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_seo_description_category_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Короткий опис сторінки в пошуковій видачі (сніпет, 140-160 символів). Якщо порожнє — автогенерація з опису категорії.', verbose_name='SEO Опис (Description)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="Ключові запити через кому (напр. 'піжами, жіноча білизна'). Якщо порожнє — генерується автоматично.", max_length=250, verbose_name='SEO Ключові слова'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Відображається у вкладці браузера та заголовку пошукової видачі Google (до 60-70 символів). Якщо порожнє — береться назва категорії.', max_length=150, verbose_name='SEO Заголовок (Title)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Короткий опис сторінки в пошуковій видачі (сніпет, 140-160 символів). Якщо порожнє — автогенерація з опису товару.', verbose_name='SEO Опис (Description)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="Ключові запити через кому (напр. 'купити піжаму, шовкова піжама'). Якщо порожнє — генерується автоматично.", max_length=250, verbose_name='SEO Ключові слова'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Відображається у вкладці браузера та заголовку пошукової видачі Google (до 60-70 символів). Якщо порожнє — береться назва товару.', max_length=150, verbose_name='SEO Заголовок (Title)'),
        ),
    ]
