# Generated by Django 5.2.7 on 2026-05-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, help_text='Оберіть кольори, в яких виготовляється цей товар. Вони використовуються для фільтрації в каталозі та вибору варіантів купівлі.', to='main.color', verbose_name='Доступні кольори'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, help_text='Оберіть розміри, які є або будуть в наявності для цього товару. Вони відображатимуться у фільтрах каталогу та як кнопки вибору на картці товару.', to='main.size', verbose_name='Доступні розміри'),
        ),
    ]
