# Generated by Django 5.2.7 on 2026-05-06 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆ (1)'), (2, '★★☆☆☆ (2)'), (3, '★★★☆☆ (3)'), (4, '★★★★☆ (4)'), (5, '★★★★★ (5)')], default=5, verbose_name='Оцінка')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=1000, verbose_name='Текст відгуку')),
                ('advantages', models.TextField(blank=True, verbose_name='Переваги')),
                ('disadvantages', models.TextField(blank=True, verbose_name='Недоліки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний (Модерація)')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Корисно (Лічильник)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.review', verbose_name='Батьківський відгук')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/images/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='Відгук')),
            ],
            options={
                'verbose_name': 'Зображення відгуку',
                'verbose_name_plural': 'Зображення відгуків',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Текст відповіді')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор (адмін)')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_replies', to='reviews.review', verbose_name='Відгук')),
            ],
            options={
                'verbose_name': 'Відповідь адміністратора',
                'verbose_name_plural': 'Відповіді адміністратора',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='reviews/videos/', verbose_name='Відео')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='reviews/thumbnails/', verbose_name="Прев'ю")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='reviews.review', verbose_name='Відгук')),
            ],
            options={
                'verbose_name': 'Відео відгуку',
                'verbose_name_plural': 'Відео відгуків',
                'ordering': ['created_at'],
            },
        ),
    ]
