# Generated by Django 5.2.7 on 2026-05-19 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=36, unique=True, verbose_name='Ref міста')),
                ('name', models.CharField(max_length=150, verbose_name='Назва міста')),
                ('area', models.CharField(blank=True, max_length=150, verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Місто Нової Пошти',
                'verbose_name_plural': 'Міста Нової Пошти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NPWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=36, unique=True, verbose_name='Ref відділення')),
                ('name', models.CharField(max_length=250, verbose_name='Назва відділення')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер відділення')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='orders.npcity', verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Відділення Нової Пошти',
                'verbose_name_plural': 'Відділення Нової Пошти',
                'ordering': ['number'],
            },
        ),
    ]
