# Generated by Django 5.2.7 on 2026-05-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fix_product_category_on_delete_and_variant_unique'),
        ('orders', '0002_npcity_npwarehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.productvariant', verbose_name='Варіант товару'),
        ),
    ]
