# Generated by Django 5.2.7 on 2026-05-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_list', models.TextField(blank=True, help_text='Вкажіть адреси через кому, пробіл або з нового рядка. Якщо порожньо, звіт буде надсилатися суперкористувачам.', verbose_name='Список email адрес')),
                ('is_active', models.BooleanField(default=True, help_text='Увімкнути або вимкнути автоматичне надсилання щоденного звіту', verbose_name='Надсилати звіт')),
            ],
            options={
                'verbose_name': 'Налаштування щоденного звіту',
                'verbose_name_plural': 'Налаштування щоденного звіту',
            },
        ),
    ]
