# Generated by Django 5.2.7 on 2026-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_salesreportsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreportsetting',
            name='email_list',
            field=models.TextField(blank=True, help_text='Вкажіть адреси через кому, пробіл або з нового рядка. Якщо порожньо, публічний звіт не буде надсилатися.', verbose_name='Список email адрес'),
        ),
    ]
