# Generated by Django 5.2.7 on 2026-05-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='liqpay_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус платежу LiqPay'),
        ),
    ]
